fastlane_require 'yaml'

fastlane_version "2.90.0"

default_platform :ios

xcode_version = '9.3'

app_identifier_internal = 'com.latam.mobile.latamapp.internal'
app_identifier_release = 'com.latam.mobile.latamapp'
app_identifier_dev = 'com.latam.mobile.latamapp.dev'

platform :ios do

  desc "Run lint on the code"
  lane :lint do
    sh "mkdir -p lint_output"
    sh "touch lint_output/lint_output.json"
    swiftlint(
      mode: :lint,
      output_file: "fastlane/lint_output/lint_output.json"
    )
    sh "cat lint_output/lint_output.json"
  end

  desc "Run all Unit Tests"
  lane :test do
    scan(scheme: "UnitTests")
    xcov(scheme: "UnitTests", skip_slack: true, minimum_coverage_percentage: 80.00)
  end

  desc "Run all UI Tests"
  lane :ui_test do
    scan(scheme: "UITests")
  end
end
